### ISSUE TITLE
Please add support for git-flow hooks

### ISSUE THREAD

**Issue by pprometey** [alirezanet/Husky.Net#10]
A collection of Git extensions to provide high-level repository operations for Vincent Driessen's branching model. This fork adds functionality not added to the original branch. https://github.com/petervanderdoes/gitflow-avh

 As of Git for Windows 2.6.4, GitFlow (AVH edition) is included

**Comment by alirezanet** [comment]
Hi, 
Thanks for the feedback, I'll check it out.

**Comment by pprometey** [comment]
>  Just a question, What did you try to do that is not currently supported?

Hi, i added 
`dotnet husky add .husky/pre-flow-feature-finish "echo 'Feature finished!'"`

It does not work through hasky, but when I add this hook to the .git/hooks folder in a project where husky is not installed, it works when I execute the command:

`git flow feature finish feature_branch` 

Gitflow hooks are not supported Hasky.net

https://github.com/petervanderdoes/gitflow-avh/blob/develop/hooks/pre-flow-feature-finish

**Comment by alirezanet** [comment]
Git has a feature `core.hooksPath` that husky is using to change the hook's path. looks like git-flow doesn't support this feature and they hardcoded it somehow! I found a project ([here](https://github.com/jaspernbrouwer/git-flow-hooks#activate)) that suggested setting `git config gitflow.path.hooks /path/to/git-flow-hooks`
which in our case should be `.husky` folder. can you check if that works or not?

**Comment by alirezanet** [comment]
It now supports gitflow, update to `v0.1.1`

![image](https://user-images.githubusercontent.com/7004080/147615066-579d5443-f0ae-4d3e-955f-3f8d796e6b4d.png)

**Comment by pprometey** [comment]
Thank you very much for such a prompt response. And for adding this feature. I use it in a real project - a very useful package!

There was also a problem in CICD when building in docker, I could not find .git, I decided that I added an empty project to the solution, which did not get into docker, but restores packages and tools locally.

**Comment by alirezanet** [comment]
> Thank you very much for such a prompt response. And for adding this feature. I use it in a real project - a very useful 

You're welcome. Happy to hear that 🙏

> There was also a problem in CICD when building in docker, I could not find .git, I decided that I added an empty project to the solution, which did not get into docker, but restores packages and tools locally.

Feel free to open a new issue, I'll check it out as soon as possible.

**Comment by alirezanet** [comment]
> There was also a problem in CICD when building in docker, I could not find .git, I decided that I added an empty project to the solution, which did not get into docker, but restores packages and tools locally.

You don't need a new project actually, you should use the environment variable `HUSKY=0` to disable husky in CI/CD pipelines
I updated[ the readme.](https://github.com/alirezanet/Husky.Net#disable-husky-in-cicd-pipelines) check it out.
