### ISSUE TITLE
not working on repos that haven't run dotnet husky install

### ISSUE THREAD

**Issue by talbananaz** [alirezanet/Husky.Net#101]
### Version

latest

### Details

Husky dotnet is not working with error unable to find git (or something along that manner) unless a user actually manually writes dotnet husky install (even though others have done this and pushed to the repo).

I assume this is due to .git folder not being in version control which is where the precommit hooks are written to, but is there a way for this to actually setup automatically? Its very odd to me that each user will need to setup husky locally unless I'm missing something and git folder shouldn't be in version control from my knowledge.

### Steps to reproduce

install husky dotnet with precommit hooks in a repo on one computer
download the repo and try command:

 dotnet husky run

**Comment by alirezanet** [comment]
Hi @talbananaz,

Have you connected Husky to your project? To install Husky for other users, you need to link the dotnet husky install command to one of your projects. This way, when the user builds their project, it will automatically set up Husky hooks.

https://alirezanet.github.io/Husky.Net/guide/automate.html

**Comment by talbananaz** [comment]
Thanks, looks good, will test :)
