### ISSUE TITLE
Support broader environmental global skip flag

### ISSUE THREAD

**Issue by Xemrox** [alirezanet/Husky.Net#32]
### Details

In an MSBuild environment its quite common to set variables to `false` instead of `0`.
Therefore I recommend to add a test to the $env:HUSKY variable for some kind of `false` in order to skip husky execution.

**Comment by Xemrox** [comment]
Late to the party but I also found this in the original husky documentation.
https://typicode.github.io/husky/#/?id=with-env-variables
Which states Husky.Net should probably check for a set $CI too.

**Comment by alirezanet** [comment]
Hi, thanks for the PR. 
I'll close this issue for now, but you can open another one about $CI if you feel we need to implement it.

this issue is fixed due to #33.
