### ISSUE TITLE
Emoji does not appear correctly in the Windows environment

### ISSUE THREAD

**Issue by acesyde** [alirezanet/Husky.Net#35]
### Version

0.4.0

### Details

When we are on the Windows environment emoji in console does not rendered correctly

Windows
![image](https://user-images.githubusercontent.com/958435/156535362-944bbe74-3f06-4f10-85ee-04dc6525eaf8.png)

Linux
![image](https://user-images.githubusercontent.com/958435/156535394-24dc73b8-236e-43cc-ac13-e5b5acb40aa4.png)

Terminal => Windows terminal
OS : Windows 11 / Ubuntu 20.04 (WSL2)

### Steps to reproduce

- Install husky
- Execute `dotnet husky run`

**Comment by acesyde** [comment]
But "Great work!" works fine Oo

![image](https://user-images.githubusercontent.com/958435/156579972-1078f778-5147-4cf8-aaf8-712925fa0665.png)

**Comment by alirezanet** [comment]
I know windows  10 and below don't support emojis but it should work fine in windows 11 at least.  
what is your terminal font? can you try a powerline to see what happens? 
![image](https://user-images.githubusercontent.com/7004080/156590073-bf6868c5-8e93-46bc-b22e-72cd2b6df919.png)

**Comment by acesyde** [comment]
I have the same behavior between windows 10 and 11 

![image](https://user-images.githubusercontent.com/958435/156594648-28a045ea-599d-47f1-8faa-404ca9801771.png)

**Comment by acesyde** [comment]
Same with monaco for powerline

![image](https://user-images.githubusercontent.com/958435/156596048-7098f7b1-6f85-4a22-a1d4-844b58441311.png)

**Comment by alirezanet** [comment]
It's weird, I never had this problem with windows 11. Is your windows terminal updated? mine is `1.11.3471.0`

**Comment by acesyde** [comment]
So after enabling this feature

![image](https://user-images.githubusercontent.com/958435/156599522-082d1b98-f72b-47b2-8d58-34b3bb696c8d.png)

Tadam

![image](https://user-images.githubusercontent.com/958435/156599563-983e9560-b15a-49ae-8314-68044adcf551.png)

**Comment by acesyde** [comment]
@alirezanet  maybe add this information in the documentation ?

**Comment by alirezanet** [comment]
Good idea 😊
