### ISSUE TITLE
Extended assembly support for execute

### ISSUE THREAD

**Issue by Xemrox** [alirezanet/Husky.Net#38]
### Details

Hello,

while writing a new csx for `husky exec` I tried to use `System.Linq` and failed to do so.
This results propably from the static assembly list here:
https://github.com/alirezanet/Husky.Net/blob/07f36179c589c825595b97116fa6fe82ab5514ab/src/Husky/Cli/ExecCommand.cs#L37-L39
How about we create a mechanism like the following in a csx file:
```csharp
// cs_reference System.Linq;
using System.Linq;
```
Which hints the execution to include that particular assembly.

Greetings
Xemrox

**Comment by alirezanet** [comment]
Hi,
We already have this feature I'm not sure why you have a problem with LINQ but for example, in this repository, I am using `using System.Text.RegularExpressions;` in commit-lint.csx file.

``` csharp
using System.Text.RegularExpressions;

private var pattern = @"^(?=.{1,90}$)(?:build|feat|ci|chore|docs|fix|perf|refactor|revert|style|test)(?:\(.+\))*(?::).{4,}(?:#\d+)*(?<![\.\s])$";
private var msg = File.ReadAllLines(Args[0])[0];

if (Regex.IsMatch(msg, pattern))
   return 0;

Console.ForegroundColor = ConsoleColor.Red;
Console.WriteLine("Invalid commit message");
Console.ResetColor();
Console.WriteLine("e.g: 'feat(scope): subject' or 'fix: subject'");
Console.ForegroundColor = ConsoleColor.Gray;
Console.WriteLine("more info: https://www.conventionalcommits.org/en/v1.0.0/");

return 1;

```

**Comment by Xemrox** [comment]
I wan't aware of the `#r` and `#load` within csscript.
Here is a broken example which can be fixed by adding a `#r "System.Linq"`
```csharp
using System.Linq;

private var test = new [] {"a", "b", "c"};
private var test2 = test.First();
```
