### ISSUE TITLE
csx return not 0 but git commit sucess finally

### ISSUE THREAD

**Issue by sampsonye** [alirezanet/Husky.Net#49]
### Version

0.5.0

### Details

![image](https://user-images.githubusercontent.com/5895634/182090787-40ffab93-871f-4e02-b098-d1ab6305ae6a.png)
` return 1;` has been executed , but the commit has been commited

may i need use `Environment.Exit(1)` replace `return 1`?

### Steps to reproduce

- offical demo
- commit 'error commit message'

**Comment by alirezanet** [comment]
Thank you for the feedback,

This problem must be solved in `v0.5.1`.

please let me know if you had other problems.
