### ISSUE TITLE
dotnet husky install fails if .git folder is in the parent folder of the #C project

### ISSUE THREAD

**Issue by mcaubrey** [alirezanet/Husky.Net#55]
### Version

v0.5.2

### Details

In my project we have a parent folder, `project` and then a child folder `Project.Api` that houses the actual C# project files.

I can install the tool as described [in the documentation](https://csharpier.com/docs/Pre-commit) but when I run `dotnet husky install` from the `Project.Api` folder I get the following output.

```
.git can't be found (see https://alirezanet.github.io/Husky.Net/guide/getting-started)
Git hooks installation failed
```

The `.git` folder is in the parent `project` folder, so I guess that makes sense. If I change directories to the parent folder and try running it again, I get,

```
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-husky does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

I attempted to install Husky globally and see if that eliminates this problem, but the output was the same afterwards.

I realize this might not be a bug and it might just be me using it in a way that was not intended. Any direction in how I could resolve this would be helpful. 

### Steps to reproduce

- Create a new dotnet project
- Put the new dotnet project inside a parent folder
- Git init inside the parent folder
- Attempt to install husky/run husky install

**Comment by alirezanet** [comment]
I think you forgot to **remove** or **update** the  dotnet format task.
```json
{
   "tasks": [
      {
         "name": "dotnet-format-example",
         "command": "dotnet",
         "args": [ "dotnet-format", "--include", "${staged}" ],
         "include": [ "**/*.cs", "**/*.vb" ]
      }, ....
```
