### ISSUE TITLE
پیشنهاد

### ISSUE THREAD

**Issue by alirezaseif28** [alirezanet/Husky.Net#6]
سلام
به نظرم در مورد کاربرد و کارایی
یه مقاله نیاز باشه
مرسی

**Comment by alirezanet** [comment]
سلام
امیدوارم [این مقاله](https://www.dntips.ir/post/3367/%da%86%d8%b1%d8%a7-%d8%a8%d8%a7%db%8c%d8%af-%d8%a7%d8%b2-git-hooks-%d8%a7%d8%b3%d8%aa%d9%81%d8%a7%d8%af%d9%87-%da%a9%d9%86%db%8c%d9%85-%d9%85%d8%b9%d8%b1%d9%81%db%8c-husky-net) کمک کند.
