### ISSUE TITLE
Doesn't support the dotnet tools (e.g jb)

### ISSUE THREAD

**Issue by aliasadidev** [alirezanet/Husky.Net#68]
### Version

0.5.4

### Details

I've installed jb tool with dotnet cli, the husky tool added a dash between dotnet and tool name; for this reason, the execution failed.
# dotnet config file
```json
{
  "version": 1,
  "isRoot": false,
  "tools": {
    "jetbrains.resharper.globaltools": {
      "version": "2022.3.2",
      "commands": [
        "jb"
      ]
    },
    "husky": {
      "version": "0.5.4",
      "commands": [
        "husky"
      ]
    }
  }
}

```
# husky's runner task
```json
 {
      "name": "Run JB Clean Up Code",
      "command": "dotnet",
      "args": [
        "jb cleanupcode myproj.sln --profile='proj: Full Cleanup'"
      ],
      "group": "pre-commit",
      "cwd": "."
    }
```

![image](https://user-images.githubusercontent.com/6399165/224016716-7a895a39-db5a-440d-9a79-5876a71055f5.png)

### Steps to reproduce

- Install jetbrains.resharper.globaltools locally with dotnet cli => ```dotnet tool install JetBrains.ReSharper.GlobalTools```
- add "jb cleanupcode myproj.sln --profile='proj: Full Cleanup'" into the arg property in the one task runner 
- this command works correctly => dotnet jb cleanupcode myproj.sln --profile='proj: Full Cleanup'

**Comment by alirezanet** [comment]
Hi @aliasadidev,
I'll take a look deeper into why this is happening, but if you separate your arguments it will work correctly, this is happening probably for different behaviors in parsing arguments for Linux, windows, and mac terminals.

```json
 "command": "dotnet",
 "args": [ "jb",  "cleanupcode",  "myproj.sln --profile='proj: Full Cleanup'" ]
```

**Comment by aliasadidev** [comment]
@alirezanet Thanks it works, I guess it would be great to mention it in documents or in the real sample.

**Comment by alirezanet** [comment]
Happy to hear that it worked, 
thanks for the feedback, also pull requests are welcome 😉😊
