### ISSUE TITLE
Can not find task-runner.json when running dotnet husky run on Windows

### ISSUE THREAD

**Issue by rafaelxvr** [alirezanet/Husky.Net#75]
### Version

v0.5.4

### Details

Hello, i'm trying to set up Husky.NET on a new project (.NET Core 6).

When running `dotnet husky run`  keeps returning the error `[Husky] ?? Loading tasks ... Can not find task-runner.json, try 'husky install'`

When i run the following commands, i get the correct paths:

`// Git Repo Path
git rev-parse --show-toplevel // returns the repo path

// Husky Relative Path
git config --get core.hooksPath // returns the .husky folder`

Already uninstalled and installed, but keeps getting the same error.

### Steps to reproduce

On Windows 10
dotnet husky install
dotnet husky run

Get error saying "Can not find task-runner.json"

**Comment by alirezanet** [comment]
Hi @rafaelxvr,

Well you repo and husky path looks ok, do have have task-runner.json file in the .husky folder?

**Comment by rafaelxvr** [comment]
Hi @alirezanet, i do have the `task-runner.json` inside the `.husky` folder, created by following the Get Started guide on documentation. Was created by the installation itself.

**Comment by rafaelxvr** [comment]
Which commands exactly @alirezanet ? the git ones?

**Comment by alirezanet** [comment]
`dotnet husky install -v`
and
`dotnet husky run -v`

**Comment by rafaelxvr** [comment]
![image](https://github.com/alirezanet/Husky.Net/assets/78372916/6ef69f70-3131-44f7-b9d1-921242a0cb4f)
![image](https://github.com/alirezanet/Husky.Net/assets/78372916/b6627f3e-f0cb-4621-9a2b-56799f219883)

Same thing, did all steps again

**Comment by alirezanet** [comment]
Hi @rafaelxvr,

This is weird! it should work but apparently, it doesn't work for you for some reason. the way we can find the problem is to either wait for the next version and let me add more verbose logs to each install steps or try to run the husky in debug mode to find what is wrong. on my machines it is working so I can not reproduce the problem.

**Comment by alirezanet** [comment]
I published a new preview version with more logs, can you please try using `v0.6.0-Preview4` version?

**Comment by rafaelxvr** [comment]
Got the problem @alirezanet, its all about special characters:

![image](https://github.com/alirezanet/Husky.Net/assets/78372916/600c1a95-ef1b-4a44-9599-d900e9ba4793)

The symbol in question is "ó", on the word Repositório which means repository in portuguese. :)
