### ISSUE TITLE
fatal: cannot run .husky/pre-commit: No such file or directory on Mac-os

### ISSUE THREAD

**Issue by Filiphasan** [alirezanet/Husky.Net#84]
### Version

0.5.4

### Details

Hi, i have an issue for v0.5.4, my project already has pre-commit file in .husky folder
![image](https://github.com/alirezanet/Husky.Net/assets/58440290/f233a58f-a451-4dd6-8c3b-3d3ab3dc96e8)

My pre-commit file is 
```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#Run the command group in .husky/task-runner.json
dotnet husky run --group pre-commit

#Allow Committing
exit 0
```
My task-runner.json file is 
```json
{
  "tasks": [
    {
      "name": "dotnet-format",
      "group": "pre-commit",
      "command": "dotnet",
      "args": ["dotnet-format", "--include", "${staged}"],
      "include": ["**/*.cs", "**/*.vb"]
    }
  ]
}
```
My .confif/dotnet-tool.json file is
```json
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "husky": {
      "version": "0.5.4",
      "commands": [
        "husky"
      ]
    },
    "dotnet-format": {
      "version": "5.1.250801",
      "commands": [
        "dotnet-format"
      ]
    }
  }
}
```

### Steps to reproduce

- I am on a branch with Husky installed in my project.
- Then, I switch to a branch without Husky installation.
- When I switch back to a branch with Husky installed and commit anything than I encounter this error.
- fatal: cannot run .husky/pre-commit: No such file or directory

It gives this error in different situations sometimes as well. For instance, I clone the project from scratch and then face this issue on a branch with Husky already installed. As far as I can understand, I encounter this error when changing branches locally.

**Comment by alirezanet** [comment]
Hi @Filiphasan,
Have you attached husky to one your projects? if not if you switch to a repo/branch that doesn't have all the husky files, you might encounter similar errors.
or just check if you manually install husky again, would it fix the problem? 
I tried to reproduce the error but it is working on my two machines.

**Comment by Filiphasan** [comment]
Hi @alirezanet 

I manually configured the Husky setup for my project with the following tag. I am experiencing the issue on macOS. When I tried it on Windows, I didn't encounter any problems. Thank you for your support.

```
<Target Name="husky" AfterTargets="Build" Condition="'$(HUSKY)' != 0">
        <Exec Command="dotnet tool restore" WorkingDirectory="../" />
        <Exec Command="dotnet husky install" WorkingDirectory="../" />
</Target>
```

**Comment by alirezanet** [comment]
Oh Unfortunately at the moment I only can test it in Linux/Windows operating systems, can you please verify if your git commit have required permissions and it is executable on mac after installing husky?

**Comment by Filiphasan** [comment]
Yes, i have already +x permission
```
ls -l .husky/pre-commit                                
-rwxr-xr-x@ 1 hasan.erdal  staff  162 Aug 25 11:20 .husky/pre-commit
```

**Comment by alirezanet** [comment]
well normally you have it, but I mean check it when you've faced the error... since the error message is:
```
fatal: cannot run .husky/pre-commit: No such file or directory
```
I think either the hook is missing for some reason or the hook doesn't have permission.

**Comment by Filiphasan** [comment]
Hi @alirezanet,

I found the cause of my issue. My project has .gitattributes file for end-of-line settings and in this file there is "* text eol=crlf" settings for all files.

My old .gitattributes file

```
# Set end-of-line to CRLF for All files.
* text eol=crlf
```

And now
```
# Set end-of-line to CRLF for All files.
* text eol=crlf

# Exclude files or folders
.husky/** -text
```

This changes has solved my "fatal: cannot run .husky/pre-commit: No such file or directory" issues.

Thanks for your support
